### ISSUE TITLE
Support .NET Standard Library

### ISSUE THREAD

**Issue by giggio** [colored-console/colored-console#62]
.NET Standard Library: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Maybe you could start with 1.1 for the .NET Standard Library, as you target 4.5 for the full framework, but maybe not everything is there, so I've seen most of the libraries moving to 1.3.
Whichever works best for you, even 1.6 would be fine for me, I want to target .NET Core, which is 1.6.

**Comment by giggio** [comment]
Superseeds #56.

**Comment by adamralph** [comment]
Thanks for raising this @giggio. Given the simplicity if the library, I'd be surprised if we couldn't target netstandard1.0. I'd probably want to keep the explicit net45 assembly in the package too so that people can use that in net45 projects without all the other dependencies (System.Console etc.) being pulled in.

I can't work on this myself for another month or so.

**Comment by giggio** [comment]
I am working on it.

**Comment by davetimmins** [comment]
v1.0.0 released, thanks @giggio 

https://www.nuget.org/packages/ColoredConsole
https://github.com/colored-console/colored-console/releases/tag/1.0.0
https://twitter.com/davetimmins/status/930613130509479937
